version: '3'

services:
  server:
    container_name: library-service
    build: '.'
    volumes:
      - ./:/node-app
      - ./node_modules:/node-app/node_modules
    environment:
      NODE_ENV: development
      PORT: 3000
      MONGO_CONNECTION: mongodb://db:27017
      DATABASE: library-service
      SECRET: TOP_SECRET

    depends_on:
      - db
    links:
      - db
    ports:
      - '3000:3000'

  db:
    image: 'mongo'
    container_name: mongo-service
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/library-service